/*
 * DIO_cnfg.c
 *
 * Created: 9/13/2019 10:49:52 AM
 *  Author: Peter
 */
#include "DIO_cnfg.h"

DIO_cnfg_t DIO_cnfg_arr[NUM_OF_PINS] = {
		{ PORT_B, PIN4, OUTPUT, LOW, NA, INITIALIZED }, //LED0
		{ PORT_B, PIN5, OUTPUT, LOW, NA, INITIALIZED }, //LED1
		{ PORT_B, PIN6, OUTPUT, LOW, NA, INITIALIZED }, //LED2
		{ PORT_B, PIN7, OUTPUT, LOW, NA, INITIALIZED }, //LED3

		{ PORT_B, PIN0, OUTPUT, LOW, NA, INITIALIZED }, //7Seg_Pin_A
		{ PORT_B, PIN1, OUTPUT, LOW, NA, INITIALIZED }, //7Seg_Pin_B
		{ PORT_B, PIN2, OUTPUT, LOW, NA, INITIALIZED }, //7Seg_Pin_C
		{ PORT_B, PIN3, OUTPUT, LOW, NA, INITIALIZED }, //7Seg_Pin_D

		{ PORT_D, PIN2, OUTPUT, LOW, NA, INITIALIZED }, //7Seg_Pin_EN1
		{ PORT_D, PIN3, OUTPUT, LOW, NA, INITIALIZED }, //7Seg_Pin_EN2
		{ PORT_D, PIN4, OUTPUT, LOW, NA, INITIALIZED }, //7Seg_Pin_DP

		};
